### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by cxm1997** [TypeFox/yang-vscode#80]
Code completion not working
I don't know if additional configurations are needed.
I want work like the first GIF image of GitHub's Features.

my env:
os: win10
vscode 1.84.2
java 11.0.19

**Comment by dhuebner** [comment]
@cxm1997 
No additional configuration is needed.
Are you sure that the language server is running? 

Note: You need to have Java 11 correctly installed on your system.

**Comment by cxm1997** [comment]
C:\Users\paul>java -version
java version "11.0.19" 2023-04-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.19+9-LTS-224, mixed mode)

My Java environment is as above.
I tested both the Win10 system and Ubuntu 20.04 system, but the completion function did not work properly.
But the error prompt, graphics, and other functions are working properly.

**Comment by dhuebner** [comment]
@cxm1997 
I see. How large is your workspace? Could you please try out with a small yang file example? 
Otherwise it would be nice to have a tiny reproducible example, so I can try it out in the dev environment.

**Comment by cxm1997** [comment]
Thank you very much for your help
I am learning Huawei Yang，GitHub repository https://github.com/ThorstenHeinze/HuaweiYangs.git
You can try using vscdoe to open and edit any yang file

**Comment by cxm1997** [comment]
The book of Network Programming with YANG: The Structure of Network Automation with YANG, NETCONF, RESTCONF, and gNMI.
This book provides a simple example of Yang, GitHub repository https://github.com/janlindblad/bookzone
You can try the 1-intro in this repository

**Comment by dhuebner** [comment]
@cxm1997 
I just installed Yangster v2.3.2 and opened your book example. A can see the content assist for built-in types. So for me it does work.  
<img width="594" alt="Bildschirmfoto 2023-11-28 um 10 28 53" src="https://github.com/TypeFox/yang-vscode/assets/454322/27cb8f35-11ca-49bf-ad25-7e8655b3727a">

**Comment by cxm1997** [comment]
I opened the debug mode of yang_language_server. bat
Then I saw the error log for Extension Host in vscode
![error](https://github.com/TypeFox/yang-vscode/assets/25753327/c21cc4ee-94c3-4b05-a116-a67e5fddc8f6)

**Comment by dhuebner** [comment]
@cxm1997 
Okay, looks like the communication goes over the websocket? 
I don't think the extension and the LS is remote usage ready. I will need to setup a test environment for that and see if it easily possible to  support this case.

**Comment by cxm1997** [comment]
Thank you for your answer. 
Could you please let me know your VScode version so that I can give it a try

**Comment by dhuebner** [comment]
@cxm1997 
I mean, it looks like you are using VS-Code with WSL (Windows-Subsystem für Linux).
It might cause the problem you see.

**Comment by cxm1997** [comment]
i disable wls. Then show error.
2023-11-30 02:12:03.100 [error] [typefox.yang-vscode] provider FAILED
2023-11-30 02:12:03.101 [error] Error: name must not be falsy
	at s.validate (e:\software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:121:17042)
	at new s (e:\software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:121:17337)
	at H (c:\Users\paul\.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:244674)
	at H (c:\Users\paul\.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:244849)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (c:\Users\paul\.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:250012)
	at c:\Users\paul\.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:27254
	at async s.provideDocumentSymbols (e:\software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:39147)

**Comment by TianliangZ-Fujitsu** [comment]
> I disable wsl. Then show error. 2023-11-30 02:12:03.100 [error] [typefox.yang-vscode] provider FAILED 2023-11-30 02:12:03.101 [error] Error: name must not be falsy at s.validate (e:\software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:121:17042) at new s (e:\software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:121:17337) at H (c:\Users\paul.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:244674) at H (c:\Users\paul.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:244849) at Array.map () at Object.asDocumentSymbols (c:\Users\paul.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:250012) at c:\Users\paul.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:27254 at async s.provideDocumentSymbols (e:\software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:39147)

Do you have the problem fixed? I have been facing the same problem.
