### ISSUE TITLE
"Couldn't start client Yang Language Server" on windows

### ISSUE THREAD

**Issue by hujun-open** [TypeFox/yang-vscode#95]
Yangster version: 2.3.2
vscode: 1.93.0
OS: windows 11

> [Error - 1:53:34 PM] Starting client failed
Error: spawn EINVAL
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:800:9)
	at c:\Users\junhu\.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:92428

I tried with openjdk 11, 21, 22, microsoft build openjdk, oracle jdk, same error

but it works fine if use vscode with WSL2 (e.g. open YANG file in WSL), with openjdk 11 installed in WSL2

**Comment by andre-brizido** [comment]
I have the same problem on windows and with
OpenJDK 64-Bit Server VM Microsoft-7208460 (build 11.0.18+10-LTS, mixed mode),
VS CODE 1.93.1
latest yangster version available

**Comment by vinsworldcom** [comment]
Could this be the issue:

https://github.com/nodejs/node/issues/52681
https://github.com/nodejs/node/issues/52554

Needs `{shell: true}` - I tried adding this but I don't really know what I'm doing.  Also tried to launch something other than `yang-language-server.bat` to no avail.

Cheers.

**Comment by vinsworldcom** [comment]
I seem to have fixed this.  First off, need a file in:

%USERPROFILE%\.yang\yang.settings:
```
{
    "yangPath": "/usr/share/yang/modules"
}
```

Where the path is the root of your Yang modules locations.  For me, they are in 'C:\usr\share\yang\modules', but I'm using the "unix"-like path which seems to work fine.

Next, you need to add the `{shell:true}` to the 'extension.js' file, around position 92366 (or where ever the:

> at c:\Users\junhu.vscode\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js:1:92428
 
line indicates, you'll find:

```
a=o.spawn(t.command,i,r)
```

I changed that to:

```
a=o.spawn(t.command,i,{shell:true})
```

And now the plugin shows the function outlines and creates diagrams!

Cheers.

**Comment by dhuebner** [comment]
@vinsworldcom 
Thanks for investigation. Seems to be a Windows issue, right? I'm on mac and will need some time to get a fix ready.

**Comment by vinsworldcom** [comment]
@dhuebner , yes, from the 2 Node.js links I reference above, seems a new Node.js setting prevents it from launching Windows `.bat` or `.cmd` files directly without setting the `{shell: true}` property.  Assuming somewhere along the recent VSCode upgrades, it started using this new Node.js version as I remember Yangster working fine for me last year and when I returned to it this year (more NETCONF/YANG work popped up), it was "broke".

Not sure you need to worry about the 'yang.settings' file, but it may be nice to make note of that in the README so Windows users know what file to create at what directory path for the Language Server to validate.

I've been happily working with my fix above for a week or so with no ill effects.  Of course, not sure of the "proper" way to fix this as I'm not a VSCode extension author or even know much about it.

Cheers.

**Comment by dhuebner** [comment]
@vinsworldcom 
The problem is that we are not launching processes directly, it must be one of the dependencies that need to be updated I think.

**Comment by vinsworldcom** [comment]
> The problem is that we are not launching processes directly

Not sure what that means.  Who creates the file:

%USERPROFILE%\extensions\typefox.yang-vscode-2.3.2\extension\pack\extension.js

Isn't that from this plugin?  That is the file that I'm editing and that is the file that is launching the ".vscode\extensions\typefox.yang-vscode-2.3.3\server\bin\yang-language-server.bat" file.  Launching that BAT file is what is generating the error - unless you make the `{shell: true}` edit to the the 'extension.js' file I indicate above.

Cheers.

**Comment by senlog** [comment]
The issue still occurs with YANGSTER 2.3.3. The above workaround of updating shell: true seems not working. 
Is there any other workaround for this? Thanks in advance. 

Pls find below the VS code details:
Version: 1.96.4 (user setup)
Commit: cd4ee3b1c348a13bafd8f9ad8060705f6d4b9cba
Date: 2025-01-16T00:16:19.038Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by vinsworldcom** [comment]
It works for me on that exact setup - Yangster 2.3.3 and VS Code 1.96.4.

**Comment by senlog** [comment]
Thank you. The issue was due to incorrect JAVA_HOME path. With the correct JAVA_HOME path and updating the extensions.js with the above suggested workaround  ( Object.assign({},t.options) ), it works fine. Thanks @vinsworldcom

**Comment by dhuebner** [comment]
@hujun-open 
A new extension v2.3.4 was released, could you please check if it is working now?

@MarvinX 
Thanks for contributing a fix!

**Comment by vinsworldcom** [comment]
@dhuebner yes, version 2.3.4 seems to have fixed this issue for me.  I no longer have to do the 'extension.js' editing hack described above.

Thank you and thank you @MarvinX !

Have a great weekend!

**Comment by dhuebner** [comment]
Closing as fixed.

**Comment by hujun-open** [comment]
> [@hujun-open](https://github.com/hujun-open) A new extension v2.3.4 was released, could you please check if it is working now?
> 
> [@MarvinX](https://github.com/MarvinX) Thanks for contributing a fix!

yes, it is working now, thanks
